apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traffic-light
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: traffic-light.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traffic-light
            port:
              number: 80
