apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traffic-light

resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: traffic-light
  version: v1
