apiVersion: v1
kind: Secret
metadata:
  name: traffic-light-secret
  namespace: traffic-light
type: Opaque
stringData:
  OIDC_CLIENT_ID: "traffic-light"
  OIDC_PROVIDER_URL: "https://sso.example.com/realms/home"
  OIDC_ISSUER: "https://sso.example.com/realms/home"
